# Generated by Django 2.1.7 on 2019-03-04 18:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherappdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcredentials',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=11),
        ),
    ]
